server:
  port: 8081

spring:
  config:
    activate:
      on-profile: pro
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host:
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host:
    port: 6379

  wechat:
    appid:
    secret: